blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/goastian/midori-desktop/discussions/new?category=feature-request
    about: Suggest an idea for Midori.
  - name: User Support
    url: https://astian.org/community/midori-browser/
    about: Support for end-user.
