name: Build Midori for Ubuntu

on:
  workflow_dispatch:

jobs:
  build-midori:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git cmake ninja-build libx11-dev libxext-dev libxrender-dev libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Clone Midori repository
        uses: actions/checkout@v3
        #run: git clone https://github.com/goastian/midori-desktop.git

      - name: Configure and build Midori
        run: |
          cd midori
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          ninja
          ninja install




